name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Publish for Linux
        run: >
          dotnet publish FrontlinePatcher
          --configuration Release
          --runtime linux-x64
          --output ./publish-linux-x64

      - name: Publish for Windows
        run: >
          dotnet publish FrontlinePatcher
          --configuration Release
          --runtime win-x64
          --output ./publish-win-x64

      - name: Package artifacts
        run: |
          zip -rj FrontlinePatcher-Linux.zip ./publish-linux-x64
          zip -rj FrontlinePatcher-Windows.zip ./publish-win-x64

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v7
        with:
          name: FrontlinePatcher-Linux.zip
          path: FrontlinePatcher-Linux.zip

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v7
        with:
          name: FrontlinePatcher-Windows.zip
          path: FrontlinePatcher-Windows.zip

  release:
    runs-on: ubuntu-latest
    needs: publish
    permissions:
      contents: write
    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v8
        with:
          name: FrontlinePatcher-Linux.zip

      - name: Download Windows artifact
        uses: actions/download-artifact@v8
        with:
          name: FrontlinePatcher-Windows.zip

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            FrontlinePatcher-Linux.zip
            FrontlinePatcher-Windows.zip